# 配置端口和项目名称
server:
  port: 8081
  servlet:
    context-path: /crm

# Spring
spring:
  http:
    encoding:
    force: true

  freemarker:
    #不缓存
    cache: false
    # 设置后缀
    suffix: .ftl
    # 相应格式
    content-type: text/html
    # 设置编码
    charset: UTF-8
    # 设置视图存储位置 ，不设置默认存放 classpath templates 目录中
    template-loader-path: classpath:/views/

  # 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: dingtianci123

  # 配置热部署
  devtools:
    restart:
      enabled: true
      # 设置重启目录，添加目录的文件需要 restart
      additional-paths: src/main/java
      # 解决项目自动重新编译后接口报404的问题
      poll-interval: 3000
      quiet-period: 1000

# 配置 mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  # 配置别名
  type-aliases-package: com.yjxxt.crm.pojo;com.yjxxt.crm.query;com.yjxxt.crm.dto;
  # 配置驼峰原则
  configuration:
    map-underscore-to-camel-case: true


# 配置插件
pagehelper:
  helper-dialect: mysql




# 配置日志
logging:
  level:
    com:
      yjxxt:
        crm:
          mapper: debug














